//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonStandardLibrary.Gen8.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonStandardLibrary.Gen8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   あくしゅう,Stench
        ///あめふらし,Drizzle
        ///かそく,Speed Boost
        ///カブトアーマー,Battle Armor
        ///がんじょう,Sturdy
        ///しめりけ,Damp
        ///じゅうなん,Limber
        ///すながくれ,Sand Veil
        ///せいでんき,Static
        ///ちくでん,Volt Absorb
        ///ちょすい,Water Absorb
        ///どんかん,Oblivious
        ///ノーてんき,Cloud Nine
        ///ふくがん,Compound Eyes
        ///ふみん,Insomnia
        ///へんしょく,Color Change
        ///めんえき,Immunity
        ///もらいび,Flash Fire
        ///りんぷん,Shield Dust
        ///マイペース,Own Tempo
        ///きゅうばん,Suction Cups
        ///いかく,Intimidate
        ///かげふみ,Shadow Tag
        ///さめはだ,Rough Skin
        ///ふしぎなまもり,Wonder Guard
        ///ふゆう,Levitate
        ///ほうし,Effect Spore
        ///シンクロ,Synchronize
        ///クリアボディ,Clear Body
        ///しぜんかいふく,Natural Cure        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ability_eng {
            get {
                return ResourceManager.GetString("Ability_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;フシギダネ&quot;: [],
        ///  &quot;フシギソウ&quot;: [],
        ///  &quot;フシギバナ&quot;: [],
        ///  &quot;フシギバナ#キョダイ&quot;: [],
        ///  &quot;ヒトカゲ&quot;: [],
        ///  &quot;リザード&quot;: [],
        ///  &quot;リザードン&quot;: [],
        ///  &quot;リザードン#キョダイ&quot;: [],
        ///  &quot;ゼニガメ&quot;: [],
        ///  &quot;カメール&quot;: [],
        ///  &quot;カメックス&quot;: [],
        ///  &quot;カメックス#キョダイ&quot;: [],
        ///  &quot;キャタピー&quot;: [],
        ///  &quot;トランセル&quot;: [],
        ///  &quot;バタフリー&quot;: [],
        ///  &quot;バタフリー#キョダイ&quot;: [],
        ///  &quot;ピカチュウ&quot;: [ &quot;プレゼント&quot;, &quot;ねがいごと&quot;, &quot;じゅうでん&quot;, &quot;ねこだまし&quot;, &quot;くすぐる&quot;, &quot;じたばた&quot;, &quot;チャームボイス&quot; ],
        ///  &quot;ピカチュウ#キョダイ&quot;: [ &quot;プレゼント&quot;, &quot;ねがいごと&quot;, &quot;じゅうでん&quot;, &quot;ねこだまし&quot;, &quot;くすぐる&quot;, &quot;じたばた&quot;, &quot;チャームボイス&quot; ],
        ///  &quot;ライチュウ&quot;: [ &quot;プレゼント&quot;, &quot;ねがいごと&quot;, &quot;じゅうでん&quot;, &quot;ねこだまし&quot;, &quot;くすぐる&quot;, &quot;じたばた&quot;, &quot;チャームボイス&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string eggMoves {
            get {
                return ResourceManager.GetString("eggMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;バタフリー&quot;: { &quot;rare&quot;: &quot;ぎんのこな&quot; },
        ///  &quot;ピカチュウ&quot;: { &quot;rare&quot;: &quot;でんきだま&quot; },
        ///  &quot;サンド&quot;: { &quot;rare&quot;: &quot;ねばりのかぎづめ&quot; },
        ///  &quot;サンドパン&quot;: { &quot;rare&quot;: &quot;ねばりのかぎづめ&quot; },
        ///  &quot;ピッピ&quot;: { &quot;rare&quot;: &quot;つきのいし&quot; },
        ///  &quot;ピクシー&quot;: { &quot;rare&quot;: &quot;つきのいし&quot; },
        ///  &quot;ロコン&quot;: { &quot;rare&quot;: &quot;もくたん&quot; },
        ///  &quot;キュウコン&quot;: { &quot;rare&quot;: &quot;もくたん&quot; },
        ///  &quot;プリン&quot;: { &quot;rare&quot;: &quot;つきのいし&quot; },
        ///  &quot;プクリン&quot;: { &quot;rare&quot;: &quot;つきのいし&quot; },
        ///  &quot;ナゾノクサ&quot;: { &quot;rare&quot;: &quot;きゅうこん&quot; },
        ///  &quot;クサイハナ&quot;: { &quot;rare&quot;: &quot;きゅうこん&quot; },
        ///  &quot;ラフレシア&quot;: { &quot;rare&quot;: &quot;きゅうこん&quot; },
        ///  &quot;ディグダ&quot;: { &quot;rare&quot;: &quot;やわらかいすな&quot; },
        ///  &quot;ダグトリオ&quot;: { &quot;rare&quot;: &quot;やわらかいすな&quot; },
        ///  &quot;ニョロゾ&quot;: { &quot;rare [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string holdingItem {
            get {
                return ResourceManager.GetString("holdingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フシギダネ,Bulbasaur
        ///フシギソウ,Ivysaur
        ///フシギバナ,Venusaur
        ///ヒトカゲ,Charmander
        ///リザード,Charmeleon
        ///リザードン,Charizard
        ///ゼニガメ,Squirtle
        ///カメール,Wartortle
        ///カメックス,Blastoise
        ///キャタピー,Caterpie
        ///トランセル,Metapod
        ///バタフリー,Butterfree
        ///ビードル,Weedle
        ///コクーン,Kakuna
        ///スピアー,Beedrill
        ///ポッポ,Pidgey
        ///ピジョン,Pidgeotto
        ///ピジョット,Pidgeot
        ///コラッタ,Rattata
        ///ラッタ,Raticate
        ///オニスズメ,Spearow
        ///オニドリル,Fearow
        ///アーボ,Ekans
        ///アーボック,Arbok
        ///ピカチュウ,Pikachu
        ///ライチュウ,Raichu
        ///サンド,Sandshrew
        ///サンドパン,Sandslash
        ///ニドラン♀,Nidoran♀
        ///ニドリーナ,Nidorina
        ///ニドクイン,Nidoqueen
        ///ニドラン♂,Nidoran♂
        ///ニドリーノ,Nidorino
        ///ニドキング,Nid [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PokeName_eng {
            get {
                return ResourceManager.GetString("PokeName_eng", resourceCulture);
            }
        }
    }
}
